name: Prettier

on: [push]

jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        env:
            CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
            CI_COMMIT_AUTHOR: Continuous Integration
        steps:
            - uses: actions/checkout@v2 # Updated to use v2 for better performance and features
            - uses: bahmutov/npm-install@v1

            - name: Run Prettier
              run: npx prettier --write --plugin=prettier-plugin-solidity 'contracts/**/*.sol'

            - uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: "dev" #optional defaults to master
