# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
        branches: ['main', 'dev']
    pull_request:
        branches: ['main', 'dev']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm install --save-dev prettier prettier-plugin-solidity
            - run: npx prettier --write --plugin=prettier-plugin-solidity 'contracts/**/*.sol'
            - run: echo "PRIVATE_KEY = b5b0c8aba0dd8c1afd7904acc1c8330be10827af8187912db8faad171db0bd90" >> .env
            - run: echo "PRIVATE_KEY2 = 98a48e976b050010adff464a090d0a8564d0b474260dca1602622c4c3c51347d" >> .env
            - run: echo "API_KEY = TMBXTZNCN21DGHCCQG9SS1Y1Q43TP3JKDV" >> .env
            - run: npx hardhat test
